### ISSUE TITLE
Fix magic method arithmetic for MultiPointerTensor w/ TF objects

### ISSUE THREAD

**Issue by jvmncs** [OpenMined/PySyft-TensorFlow#32]
Currently, magic method arithmetic doesn't work for a MultiPointerTensor to multiple TF objects. For example:
```python
x = tf.constant(2.).send(alice, bob)
print(tf.add(x, x).get())  # ==> List[Tensor(4), Tensor(4)]
y = x + x  # Raises AttributeError: 'MultiPointerTensor' object has no attribute 'add'
```
This is almost certainly due to torch-specific code left in MultiPointerTensor. Once a PR is made into PySyft moving these methods off MultiPointerTensor, and the script above is passing, this issue can be closed.

**Comment by MariaRigaki** [comment]
Not sure if anyone is working on this but I think that the problem can be solved by changing the `MultiPointerTensor` class to inherit from the `ObjectPointer` class as well (similarly to the way the PointerTensor class is defined).

From 
`class MultiPointerTensor(AbstractTensor):`

to `class MultiPointerTensor(ObjectPointer, AbstractTensor)` 

A quick change in `syft/generic/pointers/multi_pointer.py` did the trick.
