### ISSUE TITLE
Install pysyft-tensorflow with Tensorflow 1.0

### ISSUE THREAD

**Issue by MatheusMRFM** [OpenMined/PySyft-TensorFlow#40]
I'm trying to build a model using tensorflow + pysyft. My code uses TF 1.0, and when I try installing syft-tensorflow, it automatically tries to install tensorflow>=2.0.0-rc2. But this would make my code broken, since it was built for TF 1.0. My question is: is there an older version of pysyft that uses TF 1.0 or does it work only with TF 2.0?

**Comment by jvmancuso** [comment]
Hi @MatheusMRFM ! Unfortunately, PySyft only works with TensorFlow 2.x, and we have no current plans for supporting 1.x in the future.
